#!/usr/bin/env bash
# Nginx server config that redirects `/redirect_me` to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html/
touch /var/www/html/index.html
echo "Hello Word!" > /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
