#!/usr/bin/env bash
# Nginx server config: custom 404.

apt-get update
apt-get install -y nginx

mkdir /var/www/html/
echo "Hello Word!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.google.com/search?q=meteorite&source=hp&ei=5c3HY8z3EITbkgWIoYjwAQ;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
