#!/usr/bin/env bash
# Installs HAProxy version 2.4 with the following configurations:

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get update
apt-get install -y haproxy

cp -a /etc/haproxy/haproxy.cfg{,.orig}

LINE="
frontend haproxy-main
    bind *:80
    option forwardfor
    default_backend apache_webservers

backend apa
che_webservers
    balance roundrobin
    server 94238-web-01 3.90.80.107:80 check
    server 94238-web-02 52.91.115.216:80 check
"
FILE=/etc/haproxy/haproxy.cfg
#if sed -e '/frontend/,/check/!d' "$FILE" != "$LINE"; then
#  printf "%s" "$LINE" >> "$FILE"
#fi

#awk "$LINE" "$FILE" || printf "%s" "$LINE" >> "$FILE"
printf "%s" "$LINE" >> "$FILE"
service haproxy restart
