#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

function clean() {
    rm /var/run/myscript.pid
    exit
}

touch /var/run/myscript.pid
chmod +x /var/run/myscript.pid

echo $$ >> /var/run/myscript.pid

trap "echo I hate the kill command;clean" SIGTERM
trap "echo Y U no love me?!;clean" SIGINT
trap "clean" SIGQUIT

while 'true'; do
    echo "To infinity and beyond";
done
