#!/usr/bin/env bash 
#script that prints bad luck, good luck, Best School for the 4th, 8th and rest iterations
a=1
while [ $a -le 10 ];
do
    if [ "$a" == 4 ]; then
	echo "bad luck"
    elif [ "$a" == 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((a++))
done
