#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts hosts.old
echo -e '127.0.0.2\t\tlocalhost' >> hosts.new
echo -e '8.8.8.8\t\tfacebook.com' >> hosts.new
cat hosts.new > /etc/hosts
rm hosts.new
