#!/usr/bin/env bash
# Gracefully reloads Gunicorn daemon.
# shellcheck disable=SC2009
#ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
pgrep gunicorn | awk '{ print $1 }' | xargs kill -HUP
